#' Sharpen the Hypothesis Testing with Statistical Metrics #' #' This function adds a new column to any `arm` that has been passed to #' `equip()`. It only applies to `parsnip` models currently, as defined in the #' **approach** from the respective arm. It provides a test statistic on model #' fit for the original `core` data. This new column is named **metric**. It is #' intended to expand from the **tidied** column to include information about #' the overall model. See **details** for currently supported tests. #' #' It currently supports: #' #'   - `logistic_reg` = The function will return *only* the models that are #'   generated by [parsnip::logistic_reg()]. It generates a simple c-statistic
#'   (or AUC from ROC curve). The default for this is that the binary event has
#'   levels `c(0, 1)`, with the event of interest being `1` (e.g. the second
#'   event).
#'
#' @return An `octomod` object with arms outfitted with the test statistics.
#'
#' @param octomod Object of class `octomod`
#'
#' @param which_arms Vector of names of arms that should be run. Defaults to all
#'   arms that have not yet been equipped..
#'
#' @param ... To pass additional parameters as needed
#'
#' @examples
#' library(magrittr)
#' library(parsnip)
#' df <- mtcars
#' df$am <- factor(df$am)
#' df$vs <- factor(df$vs)
#'
#' om <-
#'   octomod() %>%
#'   core(df) %>%
#'   arm(
#'     title = "log_model",
#'     plan = am + vs ~ mpg + disp + hp,
#'     pattern = "parallel",
#'     approach = logistic_reg() %>% set_engine("glm"),
#'   ) %>%
#'   equip() %>%
#'   sharpen(which_arms = "log_model")
#'
#' @importFrom magrittr %>%
#' @export
sharpen <- function(octomod, which_arms = NULL, ...) {

	# Which arms to bear
	bear <- bear_arms(octomod, which_arms)

	# Get core data
	core <- octomod$core

	# Trim to appropriate arms and inventory
	status <- octomod$inventory[bear]
	arms <- octomod$arms[bear]
	equipment <- octomod$equipment[bear]

	for (i in 1:length(bear)) {

		if (inherits(status[[bear[i]]]$test$approach, "logistic_reg")) {

			equipment[[bear[i]]] <-
				equipment[[bear[i]]] %>%
				dplyr::rowwise() %>%
				mutate(pred = list({
					core %>%
						dplyr::select(outcomes) %>%
						dplyr::bind_cols(
							parsnip::predict.model_fit(fit, new_data = core, type = "prob")
						)
				})) %>%
				mutate(metric = {
					yardstick::roc_auc_vec(truth = as.factor(pred[[outcomes]]), pred[[".pred_1"]], event_level = "second")
				}) %>%
				dplyr::ungroup() %>%
				dplyr::select(-pred)

			octomod$inventory[[bear[i]]]$fit$sharpened <- TRUE
		}

	}

	# Return equipment to the octomod
	octomod[["equipment"]][bear] <- equipment[bear]

	# Return
	new_octomod(octomod)

}
